### ISSUE TITLE
AttributeError: 'InferenceData' object has no attribute 'sample_stats'

### ISSUE THREAD

**Issue by mortonjt** [flatironinstitute/q2-matchmaker#45]
This error is becoming quite common
```
Traceback (most recent call last):
  File "/mnt/home/jmorton/miniconda3/envs/qiime2-2021.4/bin/case_control_disbatch.py", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/mnt/home/jmorton/software/q2-matchmaker/scripts/case_control_disbatch.py", line 140, in <module>
    samples = merge_inferences(inf_list, 'y_predict', 'log_lhood', coords)
  File "/mnt/home/jmorton/software/q2-matchmaker/q2_matchmaker/_stan.py", line 158, in merge_inferences
    group_list.append([x.sample_stats for x in inf_list])
  File "/mnt/home/jmorton/software/q2-matchmaker/q2_matchmaker/_stan.py", line 158, in <listcomp>
    group_list.append([x.sample_stats for x in inf_list])
AttributeError: 'InferenceData' object has no attribute 'sample_stats'
deleting tmpfiles dir: /tmp/tmp2ebv7cq4
```
Its not clear exactly what is happening, but it is clear that one of the jobs failed, and requires rerunning

**Comment by mortonjt** [comment]
To facilitate debugging and finding those failed runs, you currently have to do the following
```python
import arviz as az
import glob
files = glob.glob('intermediate/*.nc')
inf_list = (az.from_netcdf(x) for x in files)
for i, inf in enumerate(inf_list):
   if not hasattr(inf, 'sample_stats'):
       print(i, files[i])
```
