### ISSUE TITLE
RuntimeError: Error during sampling

### ISSUE THREAD

**Issue by jindongmin** [flatironinstitute/q2-matchmaker#59]
```
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/mnt/home/djin/miniconda3/envs/q2_matchmaker/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/mnt/home/djin/miniconda3/envs/q2_matchmaker/lib/python3.10/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/mnt/ceph/users/djin/git/q2-matchmaker/scripts/case_control_parallel.py", line 91, in _single_func
    return _case_control_single(
  File "/mnt/ceph/users/djin/git/q2-matchmaker/q2_matchmaker/_stan.py", line 237, in _case_control_single
    fit = sm.sample(data=data_path, iter_sampling=mc_samples,
  File "/mnt/home/djin/miniconda3/envs/q2_matchmaker/lib/python3.10/site-packages/cmdstanpy/model.py", line 1190, in sample
    raise RuntimeError(msg)
RuntimeError: Error during sampling:

Command and output files:
RunSet: chains=4, chain_ids=[1, 2, 3, 4], num_processes=4
 cmd (chain 1):
	['/mnt/ceph/users/djin/git/q2-matchmaker/q2_matchmaker/assets/nb_case_control_single', 'id=1', 'random', 'seed=13536', 'data', 'file=/tmp/tmpg00gyg77/data.json', 'output', 'file=/tmp/tmpmsl2yaur/nb_case_control_singlep5ewq5s8/nb_case_control_single-20221107124807_1.csv', 'method=sample', 'num_samples=100', 'num_warmup=2000', 'algorithm=hmc', 'engine=nuts', 'max_depth=20', 'adapt', 'engaged=1', 'delta=0.95']
 retcodes=[-1, -1, -1, -1]
 per-chain output files (showing chain 1 only):
 csv_file:
	/tmp/tmpmsl2yaur/nb_case_control_singlep5ewq5s8/nb_case_control_single-20221107124807_1.csv
 console_msgs (if any):
	/tmp/tmpmsl2yaur/nb_case_control_singlep5ewq5s8/nb_case_control_single-20221107124807_0-stdout.txt
Consider re-running with show_console=True if the above output is unclear!
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/ceph/users/djin/git/q2-matchmaker/scripts/case_control_parallel.py", line 103, in <module>
    for inf in p.imap(_single_func, feature_ids, chunksize=50):
  File "/mnt/home/djin/miniconda3/envs/q2_matchmaker/lib/python3.10/multiprocessing/pool.py", line 420, in <genexpr>
    return (item for chunk in result for item in chunk)
  File "/mnt/home/djin/miniconda3/envs/q2_matchmaker/lib/python3.10/multiprocessing/pool.py", line 870, in next
    raise value
RuntimeError: Error during sampling:

Command and output files:
RunSet: chains=4, chain_ids=[1, 2, 3, 4], num_processes=4
 cmd (chain 1):
	['/mnt/ceph/users/djin/git/q2-matchmaker/q2_matchmaker/assets/nb_case_control_single', 'id=1', 'random', 'seed=13536', 'data', 'file=/tmp/tmpg00gyg77/data.json', 'output', 'file=/tmp/tmpmsl2yaur/nb_case_control_singlep5ewq5s8/nb_case_control_single-20221107124807_1.csv', 'method=sample', 'num_samples=100', 'num_warmup=2000', 'algorithm=hmc', 'engine=nuts', 'max_depth=20', 'adapt', 'engaged=1', 'delta=0.95']
 retcodes=[-1, -1, -1, -1]
 per-chain output files (showing chain 1 only):
 csv_file:
	/tmp/tmpmsl2yaur/nb_case_control_singlep5ewq5s8/nb_case_control_single-20221107124807_1.csv
 console_msgs (if any):
	/tmp/tmpmsl2yaur/nb_case_control_singlep5ewq5s8/nb_case_control_single-20221107124807_0-stdout.txt
Consider re-running with show_console=True if the above output is unclear!
```

**Comment by mortonjt** [comment]
Let's try to set `show_console=True` in the [sample method](https://github.com/flatironinstitute/q2-matchmaker/blob/main/q2_matchmaker/_stan.py#L239) to help with debugging.

**Comment by jindongmin** [comment]
Here is the new error message:
```
--- Compiling, linking C++ code ---
g++ -std=c++1y -pthread -D_REENTRANT -Wno-sign-compare -Wno-ignored-attributes      -I stan/lib/stan_math/lib/tbb_2020.3/include    -O3 -I src -I stan/src -I lib/rapidjson_1.1.0/ -I lib/CLI11-1.9.1/ -I stan/lib/stan_math/ -I stan/lib/stan_math/lib/eigen_3.3.9 -I stan/lib/stan_math/lib/boost_1.78.0 -I stan/lib/stan_math/lib/sundials_6.1.1/include -I stan/lib/stan_math/lib/sundials_6.1.1/src/sundials    -DBOOST_DISABLE_ASSERTS          -c -Wno-ignored-attributes   -x c++ -o /mnt/ceph/users/djin/git/q2-matchmaker/q2_matchmaker/assets/nb_case_control_single.o /mnt/ceph/users/djin/git/q2-matchmaker/q2_matchmaker/assets/nb_case_control_single.hpp
g++ -std=c++1y -pthread -D_REENTRANT -Wno-sign-compare -Wno-ignored-attributes      -I stan/lib/stan_math/lib/tbb_2020.3/include    -O3 -I src -I stan/src -I lib/rapidjson_1.1.0/ -I lib/CLI11-1.9.1/ -I stan/lib/stan_math/ -I stan/lib/stan_math/lib/eigen_3.3.9 -I stan/lib/stan_math/lib/boost_1.78.0 -I stan/lib/stan_math/lib/sundials_6.1.1/include -I stan/lib/stan_math/lib/sundials_6.1.1/src/sundials    -DBOOST_DISABLE_ASSERTS                -Wl,-L,"/mnt/home/djin/.cmdstan/cmdstan-2.30.1/stan/lib/stan_math/lib/tbb" -Wl,-rpath,"/mnt/home/djin/.cmdstan/cmdstan-2.30.1/stan/lib/stan_math/lib/tbb"      /mnt/ceph/users/djin/git/q2-matchmaker/q2_matchmaker/assets/nb_case_control_single.o src/cmdstan/main.o        -Wl,-L,"/mnt/home/djin/.cmdstan/cmdstan-2.30.1/stan/lib/stan_math/lib/tbb" -Wl,-rpath,"/mnt/home/djin/.cmdstan/cmdstan-2.30.1/stan/lib/stan_math/lib/tbb"   stan/lib/stan_math/lib/sundials_6.1.1/lib/libsundials_nvecserial.a stan/lib/stan_math/lib/sundials_6.1.1/lib/libsundials_cvodes.a stan/lib/stan_math/lib/sundials_6.1.1/lib/libsundials_idas.a stan/lib/stan_math/lib/sundials_6.1.1/lib/libsundials_kinsol.a  stan/lib/stan_math/lib/tbb/libtbb.so.2 -o /mnt/ceph/users/djin/git/q2-matchmaker/q2_matchmaker/assets/nb_case_control_single
/mnt/ceph/users/djin/git/q2-matchmaker/q2_matchmaker/assets/nb_case_control_single.o: file not recognized: File truncated
collect2: error: ld returned 1 exit status
make: *** [make/program:59: /mnt/ceph/users/djin/git/q2-matchmaker/q2_matchmaker/assets/nb_case_control_single] Error 1

Command ['make', '/mnt/ceph/users/djin/git/q2-matchmaker/q2_matchmaker/assets/nb_case_control_single']
	error during processing No such file or directory

multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/mnt/home/djin/miniconda3/envs/q2_matchmaker/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/mnt/home/djin/miniconda3/envs/q2_matchmaker/lib/python3.10/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/mnt/ceph/users/djin/git/q2-matchmaker/scripts/case_control_parallel.py", line 91, in _single_func
    return _case_control_single(
  File "/mnt/ceph/users/djin/git/q2-matchmaker/q2_matchmaker/_stan.py", line 217, in _case_control_single
    sm = CmdStanModel(stan_file=code)
  File "/mnt/home/djin/miniconda3/envs/q2_matchmaker/lib/python3.10/site-packages/cmdstanpy/model.py", line 214, in __init__
    raise ValueError(
ValueError: Unable to compile Stan model file: /mnt/ceph/users/djin/git/q2-matchmaker/q2_matchmaker/assets/nb_case_control_single.stan.
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/ceph/users/djin/git/q2-matchmaker/scripts/case_control_parallel.py", line 103, in <module>
    for inf in p.imap(_single_func, feature_ids, chunksize=50):
  File "/mnt/home/djin/miniconda3/envs/q2_matchmaker/lib/python3.10/multiprocessing/pool.py", line 420, in <genexpr>
    return (item for chunk in result for item in chunk)
  File "/mnt/home/djin/miniconda3/envs/q2_matchmaker/lib/python3.10/multiprocessing/pool.py", line 870, in next
    raise value
ValueError: Unable to compile Stan model file: /mnt/ceph/users/djin/git/q2-matchmaker/q2_matchmaker/assets/nb_case_control_single.stan.

```
